services:
  bubucela:
    build: .
    image: bubucela-bot
    container_name: bubucela
    restart: unless-stopped
    env_file: .env
    environment:
      STATIC_DIR: /static
    volumes:
      - ./static:/static